### ISSUE TITLE
Is it possible to buy this pcb ?

### ISSUE THREAD

**Issue by MartB** [halleysfifthinc/AVCLAN-Mockingboard#1]
Hey Sir,
I admire your work and i would really like to order the pcb because im not capable to build it myself. I just need a secondary aux input in my 2005 Toyota Aygo and i know it supports the AVC Lan protocol + has the required connectors. Sadly i have no idea what it would cost nor if it is possible for you.

Kind regards
Martin Böh

**Comment by halleysfifthinc** [comment]
@MartinBoeh I didn't actually go to the trouble of making a pcb (both because I'm lazy and because I'm a broke college student :/ ) so I just used a breadboard
